spring:
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: create.sql

            create-source: metadata

      hibernate:
        hbm2ddl:
          delimiter: ;
        
        jdbc:
          lob:
            non_contextual_creation: true

    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:postgresql://localhost:5433/db_hr_user
    username: postgres
    password: 1234567