spring:
  datasource: 
    url: jdbc:postgresql://hr-user-pg12:5432/db_hr_user
    username: postgres
    password: 1234567

  jpa:
    properties:
      hibernate: 
        jdbc: 
          lob: 
            non_contextual_creation: true

    hibernate:
      ddl-auto: none